apiVersion: skaffold/v2beta23
kind: Config
deploy:
  helm:
    releases:
      - name: dapr
        repo: https://dapr.github.io/helm-charts/
        remoteChart: dapr
      - name: postgresql
        repo: https://charts.bitnami.com/bitnami
        remoteChart: postgresql
        overrides:
          postgresqlUsername: wallet
          postgresqlPassword: walletpass
          "global.postgresql.postgresqlDatabase": wallet
